version: '3.1'
services:
  web:
    container_name: odoo16
    image: odoo:16.0
    user: root
    depends_on:
      - mydb
    ports:
      - "10016:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    restart: always             # run as a service
  mydb:
    container_name: postgres15
    image: postgres:15
    user: root
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always             # run as a service
volumes:
  odoo_data:
  odoo-db-data: