version: '3.1'
services:
  web:
    image: odoo:16.0
    user: root
    depends_on:
      - mydb
    ports:
      - "10016:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always             # run as a service
  mydb:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always             # run as a service
volumes:
  odoo-db-data: